module.exports = ({
    SET_DATA_IN_FOODITEM_LIST: 'SET_DATA_IN_FOODITEM_LIST',
    SET_DATA_IN_CARTITEM_LIST: 'SET_DATA_IN_CARTITEM_LIST',
    SET_LOADER_FOR_ORDER_VIEW: 'SET_LOADER_FOR_ORDER_VIEW',
})